---
title: "p8105_finalproject"
output: github_document
date: "2022-11-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Tentative Title 

Roe v. Wade overturn and 2022 US midterm elections: does expanding abortion bans have an impact on voter turnout?

## Proposal

Here we include our motivation for this project, anticipated data sources, intended final products, planned analyses/visualizations, and expected coding challenges.

After the Supreme Court overturned Roe v. Wade in June 2022, people had a lot of questions on what this meant for the future of reproductive rights. This quickly became an important motivating issue in all 2022 political races.  Here we seek to examine the impact of accessibility to abortion clinics on voter turnout across US states in the November 2022 midterm elections. 

Our P8105 group will be using the 2022 data on voters found [here](https://www.electproject.org/2022g) in comparison with the Myers Abortion Facility [Database](https://osf.io/8dg7r/) and Abortion Laws by State using data from [2021](https://lawatlas.org/datasets/abortion-bans) and [2022](https://ballotpedia.org/Abortion_regulations_by_state). We will also be using the [KFF](https://www.kff.org/womens-health-policy/state-indicator/mandatory-waiting-periods/?currentTimeframe=0&sortModel=%7B%22colId%22:%22Location%22,%22sort%22:%22asc%22%7D) data to identify the mandatory waiting periods and other restrictions related to abortion in each state. Specifically, we will be looking at panel distances to the nearest US abortion provider, and how this changes over time. 

Our intended final product is to create a website which has visualizations showing the change in distances to an abortion clinic within each state over time. We also plan to look at abortion bans within each state as a time series. As another visualization we are planning on showing voter turnout over time. An analysis of data we intend on doing is a linear regression model that examines the impact of abortion bans and the distance to the abortion clinics by state on voter turnout. Some possible coding challenges we may run into is combining the data sets, as well as creating a uniform time measure, which may be coded differently among each of our data sets. 

## Planned timeline

- November 12: Submit a written proposal
- November 15-18: Hold project review meeting
- November 19: begin data cleaning and tidying
- November 25: Begin analyses including EDA and visualizations, and regression
- December 1: Finalize code, disseminate results, begin report
- December 5: Finalize report, create webpage, create video 
- December 9: Final review of deliverable
- December 10: Submit written report, webpage and screencast, peer assessment 

## Group members

Our group consists of 5 members as follows:

* Abby Feinberg asf2164
* Mohammad Fouda mff2137
* Ellen Park ep3045
* Supraja Teki st3431
* Matthew Untalan mmu2108
