---
title: "visualizations"
author: "Ellen Park"
date: "2022-12-08"
output: html_document
---

```{r merge document}
library(tidyverse) 
library(tidyr)
abortionbans_df = 
  read.csv("Data/abortion_bans_final.csv") %>% 
  janitor::clean_names() 
votingturnout_df = 
  read.csv("Voting Turnout - Final.csv") %>% 
  janitor::clean_names() %>% 
  filter(!row_number() %in% c(1))
statedist_df = 
  read.csv("clinicdist_data_final/statedist_final.csv") %>% 
  janitor::clean_names() %>% 
  rename(state_abv = origin_state)
abortionvoting_df =
  full_join(abortionbans_df, votingturnout_df, by = "state_abv") %>% 
  select(-state.y) %>% 
  rename(state = state.x)
abortionvoting_df =
  full_join(abortionvoting_df, statedist_df, by = "state_abv") %>% 
  rename(clinicdistance_jun = jun, clinicdistance_jul = jul)
  
write.csv(abortionvoting_df,"Data/finalprojectfinaldataset.csv", row.names = FALSE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(knitr)
library(lubridate)
library(ggpubr)
```


```{r}
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r figure 1}
abortionvoting_df %>%
  drop_na() %>%
  ggplot(aes(x = state_abv)) +
    geom_point(aes(y = turnout_rate2018, colour = "2018")) +
    geom_point(aes(y = turnout_rate2022, colour = "2022")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Voting Turnout Rate in 2018 vs 2022",
    x = "State",
    y = "Rate Difference",
    caption = "Figure 1. Voting Turnout Rate in 2018 and 2022.")
```

```{r figure 2}
abortionvoting_df %>%
  drop_na() %>%
  ggplot(aes(x = state_abv)) +
    geom_point(aes(y = turnout_estimate2018, colour = "2018")) +
    geom_point(aes(y = turnout_estimate2022, colour = "2022")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Turnout Estimate Number in 2018 vs 2022",
    x = "State",
    y = "Rate Difference",
    caption = "Figure 2. Turnout Estimate Number in 2018 and 2022.")
```

```{r figure 3}
abortionvoting_df %>%
  drop_na() %>%
  ggplot(aes(x = state_abv)) +
    geom_point(aes(y = voting_eligible_pop2018, colour = "2018")) +
    geom_point(aes(y = voting_eligible_pop2022, colour = "2022")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Voting Eligibility Population in 2018 vs 2022",
    x = "State",
    y = "Difference",
    caption = "Figure 3. Voting Eligibility Population in 2018 and 2022.")

```
```{r figure 4}
abortionvoting_df %>%
  drop_na() %>%
  ggplot(aes(x = state_abv)) +
    geom_point(aes(y = voting_age_pop2018, colour = "2018")) +
    geom_point(aes(y = voting_age_pop2022, colour = "2022")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Voting Age Population in 2018 vs 2022",
    x = "State",
    y = "Difference",
    caption = "Figure 4. Voting Age Population in 2018 and 2022.")

```

```{r figure 5}
abortionvoting_df %>%
  drop_na() %>%
  ggplot(aes(x = state_abv)) +
  geom_point(aes(y = clinicdistance_jun, colour = "June")) +
  geom_point(aes(y = clinicdistance_jul, colour = "July")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(
    title = "Distance Changed from June to July, 2022",
    x = "State",
    y = "Distance",
    caption = "Figure 5. Average Distance from an Abortion Clinic from June to July after Overturn of Roe vs. Wade.")

```